name = "makeurownmenu"
compatibility_date = "2024-09-23"
pages_build_output_dir = "./dist"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "makeurownmenu_db"
database_name = "makeurownmenu-db"
database_id = "468cc8d5-de02-4aaa-952f-d5f204d543ec"